import { Kanit } from 'next/font/google';
import '../styles/globals.css';
import './global.css';
import Footer from '../components/Footer';
import Header from "../components/Header";


const kanit = Kanit({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin', 'vietnamese'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
